spring:
  application:
     name: recommend-engine-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 5555   # HTTP (Tomcat) port